"""Initial migration

Revision ID: 5d7797dabcdf
Revises: 
Create Date: 2026-07-06 16:28:21.909864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7797dabcdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectures',
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('lecture_summary', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lecture_quiz', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('lecture_id')
    )
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_opened', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_column('last_opened')

    op.drop_table('lectures')
    # ### end Alembic commands ###
